Several fixes

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -5,7 +5,7 @@
 
 if [ ! -d $SRCD/$nom ]; then
  install -dv $SRCD/$nom
- . $SCRD/fetch || { printf cross $nom fetch failed; exit $?; }
+ . $SCRD/fetch || { printf "cross $nom fetch failed\n"; exit $?; }
 else
  . $SCRD/verify
 fi
